name: 入江亜季 情報自動収集

on:
  schedule:
    # 日本時間 午前6時
    - cron: "0 21 * * *"

    # 日本時間 午後6時
    - cron: "0 9 * * *"

  # GitHubから手動実行
  workflow_dispatch:


# GitHub Actionsにリポジトリへの書き込みを許可
permissions:
  contents: write


jobs:

  collect:

    runs-on: ubuntu-latest

    steps:

      # =====================================================
      # リポジトリを取得
      # =====================================================

      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4


      # =====================================================
      # Pythonをセットアップ
      # =====================================================

      - name: Pythonをセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      # =====================================================
      # 必要なライブラリをインストール
      # =====================================================

      - name: 必要なライブラリをインストール
        run: |
          pip install playwright beautifulsoup4 lxml

      - name: Test Natalie
        run: python collectors/natalie_test.py

      # =====================================================
      # 北北西に曇と往け
      # =====================================================

      - name: hokuhokusei.pyを実行
        run: |
          python collectors/hokuhokusei.py


      # =====================================================
      # コミックナタリー
      # =====================================================

      - name: natalie.pyを実行
        run: |
          python collectors/natalie.py


      # =====================================================
      # 雪割草
      # =====================================================

      - name: yukiwari.pyを実行
        run: |
          python collectors/yukiwari.py


      # =====================================================
      # KADOKAWA
      # =====================================================

      - name: kadokawa.pyを実行
        run: |
          python collectors/kadokawa.py


      # =====================================================
      # アニメイトタイムズ
      # =====================================================

      - name: animatetimes.pyを実行
        run: |
          python collectors/animatetimes.py


      # =====================================================
      # news.jsonをGitHubへ保存
      # =====================================================

      - name: news.jsonをコミット
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/news.json

          git diff --cached --quiet || git commit -m "自動更新: ニュース情報を収集"

          git push